version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:9.3
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    command: -p ${POSTGRES_PORT}

volumes:
  db-data:
