version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:9.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  db_data:
